// Code generated by reading the SQL files in migrations/ — do not edit by hand.
package migrations

const SQL_0001_init = `
-- 0001_init.sql — tenants core table
CREATE SCHEMA IF NOT EXISTS tenant;

CREATE TABLE IF NOT EXISTS tenant.tenants (
    id            UUID PRIMARY KEY,
    slug          TEXT NOT NULL UNIQUE,
    name          TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'trial'
                  CHECK (status IN ('trial', 'active', 'suspended', 'deleted')),
    plan          TEXT NOT NULL DEFAULT 'starter'
                  CHECK (plan IN ('starter', 'pro', 'business', 'enterprise')),
    settings_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    branding_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    suspended_at  TIMESTAMPTZ,
    suspended_reason TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tenants_status  ON tenant.tenants(status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tenants_plan    ON tenant.tenants(plan)   WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tenants_created ON tenant.tenants(created_at DESC);

CREATE TABLE IF NOT EXISTS tenant.tenant_audit (
    id          BIGSERIAL PRIMARY KEY,
    tenant_id   UUID NOT NULL REFERENCES tenant.tenants(id) ON DELETE CASCADE,
    actor_id    TEXT,
    actor_email TEXT,
    action      TEXT NOT NULL,
    payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tenant_audit_tenant ON tenant.tenant_audit(tenant_id, created_at DESC);
`

const SQL_0002_domains_settings = `
-- 0002_domains_settings.sql — custom domain mapping & per-tenant settings

CREATE TABLE IF NOT EXISTS tenant.tenant_domains (
    id          UUID PRIMARY KEY,
    tenant_id   UUID NOT NULL REFERENCES tenant.tenants(id) ON DELETE CASCADE,
    domain      TEXT NOT NULL UNIQUE,
    type        TEXT NOT NULL DEFAULT 'custom'
                CHECK (type IN ('custom', 'subdomain', 'alias')),
    verified_at TIMESTAMPTZ,
    ssl_status  TEXT NOT NULL DEFAULT 'pending'
                CHECK (ssl_status IN ('pending', 'active', 'failed', 'expired')),
    ssl_issuer  TEXT,
    ssl_expires_at TIMESTAMPTZ,
    is_primary  BOOLEAN NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tenant_domains_tenant ON tenant.tenant_domains(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_domains_domain ON tenant.tenant_domains(domain);

CREATE TABLE IF NOT EXISTS tenant.tenant_settings (
    id          UUID PRIMARY KEY,
    tenant_id   UUID NOT NULL REFERENCES tenant.tenants(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       JSONB NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, key)
);

CREATE INDEX IF NOT EXISTS idx_tenant_settings_tenant ON tenant.tenant_settings(tenant_id);

CREATE TABLE IF NOT EXISTS tenant.tenant_branding (
    tenant_id   UUID PRIMARY KEY REFERENCES tenant.tenants(id) ON DELETE CASCADE,
    logo_url    TEXT,
    favicon_url TEXT,
    primary_color   TEXT,
    secondary_color TEXT,
    accent_color    TEXT,
    font_family     TEXT,
    custom_css      TEXT,
    email_logo_url  TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
`

const SQL_0003_usage = `
-- 0003_usage.sql — quota usage tracking

CREATE TABLE IF NOT EXISTS tenant.tenant_usage (
    tenant_id   UUID NOT NULL REFERENCES tenant.tenants(id) ON DELETE CASCADE,
    period      TEXT NOT NULL,
    metric      TEXT NOT NULL,
    value       BIGINT NOT NULL DEFAULT 0,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, period, metric)
);

CREATE INDEX IF NOT EXISTS idx_tenant_usage_period ON tenant.tenant_usage(period DESC);

CREATE TABLE IF NOT EXISTS tenant.plan_quotas (
    plan           TEXT PRIMARY KEY,
    max_users      INT NOT NULL DEFAULT 5,
    max_storage_mb INT NOT NULL DEFAULT 1024,
    max_api_calls  INT NOT NULL DEFAULT 10000,
    max_ccu        INT NOT NULL DEFAULT 50,
    features       JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO tenant.plan_quotas (plan, max_users, max_storage_mb, max_api_calls, max_ccu, features) VALUES
    ('starter',    5,      1024,  10000,    50,  '{"webauthn":true,"oauth":true,"custom_domain":false}'::jsonb),
    ('pro',        50,     10240, 100000,   200, '{"webauthn":true,"oauth":true,"custom_domain":true}'::jsonb),
    ('business',   500,    51200, 1000000,  1000,'{"webauthn":true,"oauth":true,"custom_domain":true,"sso":true}'::jsonb),
    ('enterprise', 999999, 1024000, 99999999, 99999, '{"webauthn":true,"oauth":true,"custom_domain":true,"sso":true,"audit_log":true}'::jsonb)
ON CONFLICT (plan) DO NOTHING;
`
