"""Runbook writer via Confluence REST API."""
from __future__ import annotations

import base64
import os
from typing import Any

import httpx

from app.core import get_logger

CONFLUENCE_URL = os.getenv("CONFLUENCE_URL", "https://rinco.atlassian.net/wiki")
CONFLUENCE_USER = os.getenv("CONFLUENCE_USER", "")
CONFLUENCE_TOKEN = os.getenv("CONFLUENCE_TOKEN", "")
CONFLUENCE_SPACE = os.getenv("CONFLUENCE_SPACE", "RINCO")
TIMEOUT = 15.0

logger = get_logger("runbook_writer")


async def create_runbook(
    title: str,
    content_html: str,
    space: str = "RINCO",
    parent_id: str | None = None,
) -> str:
    """
    Create a runbook page in Confluence.

    Args:
        title: Page title.
        content_html: HTML body of the runbook page.
        space: Confluence space key. Defaults to "RINCO".
        parent_id: Optional parent page ID for nesting.

    Returns:
        URL of the created Confluence page, or empty string on failure.
    """
    if not CONFLUENCE_USER or not CONFLUENCE_TOKEN:
        logger.warning("confluence_credentials_missing")
        return ""

    try:
        body: dict[str, Any] = {
            "type": "page",
            "title": title,
            "space": {"key": space},
            "body": {
                "storage": {
                    "value": content_html,
                    "representation": "storage",
                }
            },
        }
        if parent_id:
            body["ancestors"] = [{"id": parent_id}]

        async with httpx.AsyncClient(timeout=TIMEOUT) as client:
            auth_bytes = f"{CONFLUENCE_USER}:{CONFLUENCE_TOKEN}".encode()
            auth_b64 = base64.b64encode(auth_bytes).decode()
            r = await client.post(
                f"{CONFLUENCE_URL}/rest/api/content",
                json=body,
                headers={
                    "Authorization": f"Basic {auth_b64}",
                    "Content-Type": "application/json",
                    "Accept": "application/json",
                },
            )
            r.raise_for_status()
            data = r.json()
            page_url = f"{CONFLUENCE_URL}/pages/viewpage.action?pageId={data.get('id', '')}"
            logger.info("confluence_page_created", title=title, url=page_url)
            return page_url

    except httpx.HTTPStatusError as e:
        logger.warning("confluence_create_failed", status=e.response.status_code, title=title)
        return ""
    except Exception as e:
        logger.warning("confluence_create_error", title=title, error=str(e))
        return ""


def build_runbook_html(
    incident_id: str,
    service: str,
    root_cause: str,
    suggested_fix: str,
    prevention: str,
    metrics: dict[str, Any],
    logs: list[dict[str, Any]],
) -> str:
    """
    Build an HTML runbook body from incident analysis data.

    Args:
        incident_id: Identifier for the incident.
        service: Affected service name.
        root_cause: Root cause description.
        suggested_fix: Code-level fix suggestion.
        prevention: Preventive measures.
        metrics: Key metric snapshots.
        logs: Sample error log entries.

    Returns:
        HTML string suitable for Confluence storage representation.
    """
    error_log_rows = ""
    for log in logs[:20]:
        msg = log.get("message", "")[:300]
        ts = log.get("timestamp", "")
        error_log_rows += f"<tr><td>{ts}</td><td><code>{_escape_html(msg)}</code></td></tr>\n"

    metrics_rows = ""
    for key, value in metrics.items():
        metrics_rows += f"<tr><td>{key}</td><td>{value}</td></tr>\n"

    return f"""<h1>Incident Runbook: {service}</h1>

<p><strong>Incident ID:</strong> {incident_id}<br/>
<strong>Service:</strong> {service}<br/>
<strong>Generated:</strong> {imported_datetime()}</p>

<h2>Root Cause</h2>
<p>{_escape_html(root_cause)}</p>

<h2>Suggested Fix</h2>
<pre><code>{_escape_html(suggested_fix)}</code></pre>

<h2>Prevention</h2>
<p>{_escape_html(prevention)}</p>

<h2>Key Metrics</h2>
<table>
<thead><tr><th>Metric</th><th>Value</th></tr></thead>
<tbody>
{metrics_rows or '<tr><td colspan="2">No metrics available</td></tr>'}
</tbody>
</table>

<h2>Error Logs (Sample)</h2>
<table>
<thead><tr><th>Timestamp</th><th>Message</th></tr></thead>
<tbody>
{error_log_rows or '<tr><td colspan="2">No logs available</td></tr>'}
</tbody>
</table>

<hr/>
<em>Auto-generated by AI SRE Worker. Please review before publishing.</em>
"""


def _escape_html(text: str) -> str:
    """Simple HTML escaping for runbook content."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def imported_datetime() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
