#!/bin/bash
# ============================================================
# WireGuard mesh setup — RINCO
# ============================================================
# Usage:
#   wg-mesh.sh <node-ip> <node-name> [--peer <peer-ip>:<peer-pubkey>]
#
# Examples:
#   wg-mesh.sh 10.100.0.1 node1
#   wg-mesh.sh 10.100.0.2 node2 --peer 10.100.0.1:PUBKEY_OF_NODE1
#
# WireGuard keys are EXAMPLE PLACEHOLDERS only. In production,
# use the setup-mesh.sh onboarding script in infra/wireguard/
# to provision real keys for tenant VPS nodes.
# ============================================================

set -euo pipefail

NODE_IP="${1:-}"
NODE_NAME="${2:-}"

if [ -z "${NODE_IP}" ] || [ -z "${NODE_NAME}" ]; then
    echo "Usage: $0 <node-ip> <node-name> [--peer <peer-ip>:<peer-pubkey>]"
    exit 1
fi

shift 2

WG_DIR="/etc/wireguard"
WG_IFACE="wg0"
WG_PORT="51820"

# Ensure WireGuard is installed
if ! command -v wg >/dev/null 2>&1; then
    echo "WireGuard not installed. Installing..."
    if command -v apt-get >/dev/null 2>&1; then
        DEBIAN_FRONTEND=noninteractive apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq wireguard
    elif command -v yum >/dev/null 2>&1; then
        yum install -y -q wireguard-tools
    else
        echo "Please install wireguard-tools manually." >&2
        exit 1
    fi
fi

mkdir -p "${WG_DIR}"

# Generate keys if missing
if [ ! -f "${WG_DIR}/private.key" ]; then
    wg genkey | tee "${WG_DIR}/private.key" | wg pubkey > "${WG_DIR}/public.key"
    chmod 600 "${WG_DIR}/private.key"
    chmod 644 "${WG_DIR}/public.key"
fi

PRIVATE_KEY=$(cat "${WG_DIR}/private.key")
PUBLIC_KEY=$(cat "${WG_DIR}/public.key")

echo "==> Node ${NODE_NAME} public key: ${PUBLIC_KEY}"

# Build peer list
PEER_BLOCKS=""
while [ $# -gt 0 ]; do
    case "$1" in
        --peer)
            shift
            PEER="${1}"
            PEER_IP="${PEER%%:*}"
            PEER_PUB="${PEER##*:}"
            PEER_BLOCKS="${PEER_BLOCKS}
[Peer]
PublicKey = ${PEER_PUB}
Endpoint = ${PEER_IP}:${WG_PORT}
AllowedIPs = ${PEER_IP}/32, 10.200.0.0/24
PersistentKeepalive = 25
"
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# Compose interface config
cat > "${WG_DIR}/${WG_IFACE}.conf" <<EOF
# RINCO WireGuard — generated by wg-mesh.sh
# Node: ${NODE_NAME}  IP: ${NODE_IP}
[Interface]
Address = ${NODE_IP}/24
ListenPort = ${WG_PORT}
PrivateKey = ${PRIVATE_KEY}

# Masquerade traffic leaving this node
PostUp = iptables -t nat -A POSTROUTING -s 10.100.0.0/24 -o eth0 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.100.0.0/24 -o eth0 -j MASQUERADE

# --- Peer list ---
${PEER_BLOCKS}
EOF

chmod 600 "${WG_DIR}/${WG_IFACE}.conf"

# Bring up the interface
if command -v systemctl >/dev/null 2>&1; then
    systemctl enable --now "wg-quick@${WG_IFACE}"
else
    wg-quick up "${WG_IFACE}"
fi

echo "==> WireGuard mesh configured for ${NODE_NAME}"
echo "    Interface: ${WG_IFACE}"
echo "    Address:   ${NODE_IP}/24"
echo "    Listen:    ${WG_PORT}/udp"
echo "    PublicKey: ${PUBLIC_KEY}"
echo ""
echo "Add this public key to peer nodes:"
echo "    wg-mesh.sh <peer-ip> <peer-name> --peer ${NODE_IP}:${PUBLIC_KEY}"
