apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    isDefault: false
    jsonData:
      maxLines: 1000
      tlsSkipVerify: true
      timeout: 60
      queryTimeout: 60s
      httpHeaders:
        X-Scope-OrgID: 'tenant'
