apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    isDefault: false
    jsonData:
      httpHeaders:
        X-Scope-OrgID: 'tenant'
      tlsSkipVerify: true
      timeout: 60
      tracesToLogs:
        datasourceUid: 'loki'
      serviceMap:
        datasourceUid: 'prometheus'
