apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rinco.fullname" . }}-common
  labels:
    {{- include "rinco.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.configMap.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
