{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rinco.fullname" . }}
  labels:
    {{- include "rinco.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "rinco.selectorLabels" . | nindent 5 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: traefik
      ports:
        - protocol: TCP
          port: http
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 4222
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 4317
{{- end }}
