"""Train a dummy XGBoost lead-scoring model.

This script produces a synthetic binary classifier used as the default
``lead_scoring.json`` model when no real training data is available
yet.  It exists so the ``lead-scoring`` service always has a model
file to load — the inference code (``app.services.inference``) checks
``models/lead_scoring.json`` at startup.

Run::

    python scripts/train_dummy.py

The script writes the model to ``models/lead_scoring.json`` next to
the project root (``services/lead-scoring``).

Replace the synthetic data with real leads + labels once the
``leads`` table has enough history.
"""
from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pandas as pd
from xgboost import XGBClassifier


FEATURE_COLUMNS = [
    "source_score",          # 0..1 — lead-source quality
    "page_visits",           # 0..20 — session engagement
    "time_on_page_seconds",  # raw seconds
    "has_phone",             # 0/1
    "has_email",             # 0/1
    "has_company",           # 0/1
    "estimated_value_log",   # log of estimated deal value
    "form_length",           # how many fields filled
    "utm_source_score",      # 0..1 — paid/organic/social
    "returning_visitor",     # 0/1
]


def build_synthetic_dataset(n_samples: int = 5000, seed: int = 42) -> tuple[pd.DataFrame, np.ndarray]:
    """Build a deterministic synthetic dataset.

    The labels are generated by a noisy linear combination of the
    features so the model has something learnable.  The mapping is
    deliberately simple — the goal is to produce *a* working
    classifier, not to achieve state-of-the-art accuracy.
    """
    rng = np.random.default_rng(seed)

    df = pd.DataFrame(
        {
            "source_score": rng.uniform(0, 1, n_samples),
            "page_visits": rng.integers(0, 21, n_samples).astype(float),
            "time_on_page_seconds": rng.exponential(scale=120, size=n_samples),
            "has_phone": rng.integers(0, 2, n_samples).astype(float),
            "has_email": rng.integers(0, 2, n_samples).astype(float),
            "has_company": rng.integers(0, 2, n_samples).astype(float),
            "estimated_value_log": rng.uniform(0, 6, n_samples),
            "form_length": rng.integers(1, 8, n_samples).astype(float),
            "utm_source_score": rng.uniform(0, 1, n_samples),
            "returning_visitor": rng.integers(0, 2, n_samples).astype(float),
        }
    )

    # Hand-crafted scoring signal: combine the top features with
    # different weights, add Gaussian noise, then binarize at 0.5.
    raw = (
        0.30 * df["source_score"]
        + 0.05 * df["page_visits"]
        + 0.001 * df["time_on_page_seconds"]
        + 0.20 * df["has_phone"]
        + 0.20 * df["has_email"]
        + 0.15 * df["has_company"]
        + 0.10 * (df["estimated_value_log"] / 6.0)
        + 0.05 * (df["form_length"] / 7.0)
        + 0.05 * df["utm_source_score"]
        + 0.10 * df["returning_visitor"]
        + rng.normal(0, 0.10, n_samples)
    )

    y = (raw > 0.5).astype(int)
    return df, y


def main() -> None:
    here = Path(__file__).resolve().parent.parent  # services/lead-scoring
    models_dir = here / "models"
    models_dir.mkdir(parents=True, exist_ok=True)

    print(f"[train_dummy] generating synthetic dataset...")
    X, y = build_synthetic_dataset()

    print(f"[train_dummy] fitting XGBClassifier on {len(X)} samples / {len(FEATURE_COLUMNS)} features")
    model = XGBClassifier(
        n_estimators=120,
        max_depth=4,
        learning_rate=0.1,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42,
    )
    model.fit(X, y)

    out_path = models_dir / "lead_scoring.json"
    model.save_model(str(out_path))
    print(f"[train_dummy] model saved to {out_path}")

    # Quick sanity check
    train_acc = float((model.predict(X) == y).mean())
    print(f"[train_dummy] in-sample accuracy: {train_acc:.3f}")


if __name__ == "__main__":
    main()
